apiVersion: v1
data:
  statsd_mapping.conf: |
    mappings:
      - match: "velero.backup.active.total.*"
        name: "velero_backup_active_total"
        labels:
          schedule: "$1"
kind: ConfigMap
metadata:
  name: statsd-mapping
  namespace: velero
